version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: canil-db
    restart: always
    environment:
      POSTGRES_DB: canil_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: